// issue-examples/items-are-not-synced/main/gui/Inventory.vue
<template>
</template>

<script lang="ts">
    export default {
        name: 'inventory',
        inject: ['rpgCurrentPlayer'],
        mounted() {
            this.rpgCurrentPlayer.subscribe(({ object }) => {
                console.log('frontend', object.items);
            })
        }
    }
</script>

// issue-examples/items-are-not-synced/main/gui/Inventory.tsx
import { RpgReactContext } from "@rpgjs/client/react";
import { useContext, useEffect } from "react";

export default function Inventory() {
    const { rpgCurrentPlayer } = useContext(RpgReactContext);

    useEffect(() => {
        const subscription = rpgCurrentPlayer.subscribe(({ object }) => {
            console.log(object.items);
        });

        return () => subscription.unsubscribe();
    }, []);
}
